/**
 * SYNTHETIC DEMO DATA — Ravi Kumar
 * This is clearly synthetic/demo data. No real patient information.
 */

export const DEMO_PATIENT_ID = 'demo-ravi-kumar-001';

export const demoPatient = {
  id: DEMO_PATIENT_ID,
  firstName: 'Ravi',
  lastName: 'Kumar',
  dateOfBirth: '1950-03-15',
  gender: 'Male',
  phone: '+91-98765-43210',
  email: 'ravi.kumar@example.com',
  address: 'HSR Layout, Bangalore, Karnataka',
  emergencyContactName: 'Ananya Kumar',
  emergencyContactPhone: '+91-98765-00001',
  primaryDoctor: 'Dr. Priya Sharma',
  lastClinicalReview: '2026-08-28',
  careCircleCount: 6,
  status: 'ACTIVE',
  // DEMO label — clearly synthetic
  _demo: true,
  _disclaimer: 'SYNTHETIC DEMO DATA — Not a real patient',
};

export const demoYearTimeline = {
  patientId: DEMO_PATIENT_ID,
  currentYear: 2026,
  years: [
    {
      year: 2020,
      status: 'GOOD',
      label: 'Good',
      summary: 'Stable year. Regular medications, no hospitalizations. Minor seasonal illness in March.',
      reasons: ['No significant health events', 'Good medication adherence (96%)', 'Regular mobility'],
      eventCount: 3,
    },
    {
      year: 2021,
      status: 'STABLE',
      label: 'Stable',
      summary: 'Managed hypertension and type 2 diabetes well. Started new antihypertensive in June.',
      reasons: ['Medication adjustment', 'Good adherence', 'Stable blood pressure readings'],
      eventCount: 8,
    },
    {
      year: 2022,
      status: 'GOOD',
      label: 'Good',
      summary: 'Excellent year overall. Consistent walking routine, 98% medication adherence.',
      reasons: ['High medication adherence', 'Active lifestyle', 'No hospitalizations'],
      eventCount: 5,
    },
    {
      year: 2023,
      status: 'WATCH',
      label: 'Watch',
      summary: 'Near fall in April. Mobility decreased slightly. Medication change in September.',
      reasons: ['Near fall event', 'Mild mobility decline', 'Medication adjustment'],
      eventCount: 12,
    },
    {
      year: 2024,
      status: 'CONCERN',
      label: 'Concern',
      summary: 'Fall in February. ER visit. Medication changes. Functional decline noted by caregiver.',
      reasons: ['Fall requiring ER visit', 'Medication changes', 'Functional decline', 'Care Circle reports of fatigue'],
      eventCount: 22,
    },
    {
      year: 2025,
      status: 'CRITICAL',
      label: 'Critical',
      summary: 'Hospitalization in March (pneumonia). Significant functional decline. Fall in August.',
      reasons: [
        'Hospitalization (pneumonia)',
        'Second fall with minor injury',
        'Multiple medication changes',
        'Significant functional decline',
        'Increased Care Circle observations',
      ],
      eventCount: 38,
    },
    {
      year: 2026,
      status: 'WATCH',
      label: 'Watch',
      summary: 'Meaningful changes detected this year. Medication adherence down. Mobility reduced. Confusion reports.',
      reasons: [
        'Medication changed 8 days ago',
        'Medication adherence decreased to 72%',
        'Mobility below personal baseline',
        'Appetite decreased',
        '4 confusion-related observations',
        'Similar pattern to 2024 episode',
      ],
      eventCount: 14,
    },
  ],
};

export const demoYearDetail: Record<number, unknown> = {
  2026: {
    year: 2026,
    status: 'WATCH',
    summary: 'Meaningful changes detected in medication adherence, mobility, appetite and cognitive observations.',
    metrics: {
      medicationAdherence: { current: 72, baseline: 95, unit: '%', trend: 'down' },
      mobility: { current: 1950, baseline: 3100, unit: 'steps/day', trend: 'down' },
      appetite: { current: 'Reduced', baseline: 'Normal', unit: '', trend: 'down' },
      sleep: { current: 5.4, baseline: 7, unit: 'hrs', trend: 'down' },
      confusionReports: { current: 4, baseline: 0, unit: 'reports', trend: 'up', baselineLabel: 'Rare' },
      functionalStatus: { current: 'Needs support', baseline: 'Independent', unit: '', trend: 'down' },
    },
    events: [
      {
        id: 'ev-2026-001',
        type: 'COGNITIVE_CHANGE',
        date: '2026-09-10',
        description: 'Increased confusion reported by daughter',
        reporter: 'Ananya Kumar',
        relationship: 'Daughter',
        source: 'Care Circle',
        status: 'REPORTED',
        icon: '🧠',
      },
      {
        id: 'ev-2026-002',
        type: 'MISSED_MEDICATION',
        date: '2026-09-08',
        description: 'Missed evening medication (Amlodipine 5mg)',
        reporter: 'Ananya Kumar',
        relationship: 'Daughter',
        source: 'Care Circle',
        status: 'REPORTED',
        icon: '💊',
      },
      {
        id: 'ev-2026-003',
        type: 'APPETITE_CHANGE',
        date: '2026-09-06',
        description: 'Reduced appetite — ate very little at dinner',
        reporter: 'Latha (Caregiver)',
        relationship: 'Professional Caregiver',
        source: 'Care Circle',
        status: 'REPORTED',
        icon: '🍽️',
      },
      {
        id: 'ev-2026-004',
        type: 'SLEEP_CHANGE',
        date: '2026-09-04',
        description: 'Sleeping less than usual, wakes up at night',
        reporter: 'Rahul Mehta',
        relationship: 'Friend',
        source: 'Care Circle',
        status: 'REPORTED',
        icon: '😴',
      },
      {
        id: 'ev-2026-005',
        type: 'MOBILITY_CHANGE',
        date: '2026-09-02',
        description: 'Has not taken morning walk this week',
        reporter: 'Meena Iyer',
        relationship: 'Neighbor',
        source: 'Care Circle',
        status: 'REPORTED',
        icon: '🚶',
      },
      {
        id: 'ev-2026-006',
        type: 'MEDICATION_CHANGED',
        date: '2026-09-02',
        description: 'Metformin dose adjusted by Dr. Priya Sharma',
        reporter: 'Dr. Priya Sharma',
        relationship: 'Clinician',
        source: 'Clinical Record',
        status: 'VERIFIED',
        icon: '💊',
      },
      {
        id: 'ev-2026-007',
        type: 'COGNITIVE_CHANGE',
        date: '2026-08-28',
        description: 'Asked the same question multiple times during visit',
        reporter: 'Suresh Kumar',
        relationship: 'Son',
        source: 'Care Circle',
        status: 'REPORTED',
        icon: '🧠',
      },
      {
        id: 'ev-2026-008',
        type: 'LAB_RESULT',
        date: '2026-08-20',
        description: 'HbA1c: 7.8% (above target). Creatinine slightly elevated.',
        reporter: 'Clinical Lab',
        relationship: 'Lab',
        source: 'Clinical Record',
        status: 'VERIFIED',
        icon: '🔬',
      },
    ],
    careCircleReports: [
      {
        id: 'cc-001',
        reporter: 'Ananya Kumar',
        relationship: 'Daughter',
        avatar: 'AK',
        text: 'Dad forgot his evening medicine yesterday. He seemed confused about what day it was.',
        date: '2026-09-10T08:30:00Z',
        category: 'MEDICATION',
        status: 'REPORTED',
      },
      {
        id: 'cc-002',
        reporter: 'Rahul Mehta',
        relationship: 'Friend',
        avatar: 'RM',
        text: 'Met uncle today. He seemed more tired than usual and had less energy for conversation.',
        date: '2026-09-09T16:00:00Z',
        category: 'OTHER',
        status: 'REPORTED',
      },
      {
        id: 'cc-003',
        reporter: 'Meena Iyer',
        relationship: 'Neighbor',
        avatar: 'MI',
        text: "He hasn't been taking his normal morning walk all week. Very unusual for him.",
        date: '2026-09-08T10:00:00Z',
        category: 'MOBILITY',
        status: 'REPORTED',
      },
      {
        id: 'cc-004',
        reporter: 'Suresh Kumar',
        relationship: 'Son',
        avatar: 'SK',
        text: 'Called Papa today. He repeated the same question about my work three times in 10 minutes.',
        date: '2026-09-08T20:00:00Z',
        category: 'CONFUSION',
        status: 'REPORTED',
      },
      {
        id: 'cc-005',
        reporter: 'Latha Reddy',
        relationship: 'Professional Caregiver',
        avatar: 'LR',
        text: 'Morning medication was still in the pill box when I arrived. He says he forgot.',
        date: '2026-09-07T09:00:00Z',
        category: 'MEDICATION',
        status: 'REPORTED',
      },
    ],
    clinicalTakeaways: [
      'Medication change 8 days ago coincides with adherence and appetite changes',
      '3 independent Care Circle members reported confusion-related observations within 7 days',
      'Mobility is 37% below personal baseline — strongest deviation in 2 years',
      'Pattern similarity to 2024 episode (medication change → appetite → mobility → fall)',
      'HbA1c elevated at 7.8% — recent lab supports metabolic concern',
    ],
  },
  2025: {
    year: 2025,
    status: 'CRITICAL',
    summary: 'Most significant year. Hospitalization for pneumonia in March. Second fall in August with injury.',
    metrics: {
      medicationAdherence: { current: 88, baseline: 95, unit: '%', trend: 'down' },
      mobility: { current: 2200, baseline: 3100, unit: 'steps/day', trend: 'down' },
      appetite: { current: 'Poor (hospitalization)', baseline: 'Normal', unit: '', trend: 'down' },
      sleep: { current: 6.0, baseline: 7, unit: 'hrs', trend: 'down' },
    },
    events: [
      {
        id: 'ev-2025-001',
        type: 'HOSPITALIZATION',
        date: '2025-03-15',
        description: 'Admitted for pneumonia. 8-day hospital stay. IV antibiotics.',
        source: 'Clinical Record',
        status: 'VERIFIED',
        icon: '🏥',
      },
      {
        id: 'ev-2025-002',
        type: 'FALL',
        date: '2025-08-22',
        description: 'Fall in bathroom. Minor wrist injury. No fracture.',
        reporter: 'Latha Reddy',
        relationship: 'Caregiver',
        source: 'Care Circle + Clinical Record',
        status: 'VERIFIED',
        icon: '⚠️',
      },
      {
        id: 'ev-2025-003',
        type: 'MEDICATION_CHANGED',
        date: '2025-03-28',
        description: 'Post-hospitalization: 3 medication changes. Added respiratory medication.',
        source: 'Clinical Record',
        status: 'VERIFIED',
        icon: '💊',
      },
      {
        id: 'ev-2025-004',
        type: 'FUNCTIONAL_CHANGE',
        date: '2025-06-10',
        description: 'Needs assistance with bathing since hospitalization. Previously independent.',
        source: 'Care Circle',
        status: 'REPORTED',
        icon: '🦽',
      },
    ],
  },
};

export const demoBaseline = {
  patientId: DEMO_PATIENT_ID,
  status: 'COMPUTED',
  computedAt: '2026-09-10T00:00:00Z',
  _demo: true,
  metrics: [
    {
      metric: 'WALKING',
      label: 'Daily Steps',
      normalRange: '2,800 – 3,400 steps/day',
      current: '1,950 steps/day',
      currentValue: 1950,
      baselineValue: 3100,
      change: -37,
      trend: 'down',
      unit: 'steps/day',
      periodDays: 90,
      confidence: 'HIGH',
      sampleCount: 87,
      description: 'Typical morning walk + afternoon activity. Consistent 6-day routine.',
    },
    {
      metric: 'MEDICATION_ADHERENCE',
      label: 'Medication Adherence',
      normalRange: '93 – 97%',
      current: '72%',
      currentValue: 72,
      baselineValue: 95,
      change: -23,
      trend: 'down',
      unit: '%',
      periodDays: 90,
      confidence: 'HIGH',
      sampleCount: 270,
      description: 'Historically takes all medications reliably. Manages independently.',
    },
    {
      metric: 'SLEEP',
      label: 'Sleep Duration',
      normalRange: '6.5 – 7.5 hrs',
      current: '5.4 hrs',
      currentValue: 5.4,
      baselineValue: 7,
      change: -23,
      trend: 'down',
      unit: 'hrs',
      periodDays: 90,
      confidence: 'MODERATE',
      sampleCount: 42,
      description: 'Usually sleeps 10:30 PM – 6 AM with occasional short naps.',
    },
    {
      metric: 'APPETITE',
      label: 'Appetite',
      normalRange: 'Good',
      current: 'Reduced',
      currentValue: null,
      baselineValue: null,
      change: null,
      trend: 'down',
      unit: '',
      periodDays: 90,
      confidence: 'MODERATE',
      sampleCount: 38,
      description: 'Typically eats 3 meals with good appetite. Enjoys traditional South Indian food.',
    },
    {
      metric: 'COGNITION',
      label: 'Cognitive Observations',
      normalRange: 'Rare (0–1/month)',
      current: '4 reports (past 2 weeks)',
      currentValue: 4,
      baselineValue: 0.5,
      change: 700,
      trend: 'up',
      unit: 'reports/2wk',
      periodDays: 90,
      confidence: 'MODERATE',
      sampleCount: 26,
      description: 'Historically sharp. Occasional forgetfulness but quickly self-corrects.',
    },
    {
      metric: 'MOOD',
      label: 'Mood',
      normalRange: 'Positive',
      current: 'Subdued',
      currentValue: null,
      baselineValue: null,
      change: null,
      trend: 'down',
      unit: '',
      periodDays: 90,
      confidence: 'LOW',
      sampleCount: 12,
      description: 'Generally cheerful. Enjoys social interactions and family visits.',
    },
  ],
};

export const demoEpisodes = [
  {
    id: 'ep-001',
    title: '2024 Fall Episode',
    startDate: '2024-01-20',
    endDate: '2024-04-15',
    outcome: 'Resolved with ER visit and physical therapy',
    severity: 'CONCERN',
    _demo: true,
    symptoms: ['Reduced appetite', 'Mobility decline', 'Fatigue', 'Dizziness'],
    medicationsInvolved: ['Metformin adjusted', 'Added Vitamin D'],
    pattern: [
      { event: 'Medication changed', date: '2024-01-20' },
      { event: 'Appetite reduced', date: '2024-01-28' },
      { event: 'Mobility reduced', date: '2024-02-05' },
      { event: 'Dizziness reported', date: '2024-02-10' },
      { event: 'Fall — ER visit', date: '2024-02-18' },
    ],
    similarityScore: 0.82,
    similarityLabel: 'Strong pattern similarity',
    warning:
      'Pattern similarity does not establish causation or predict the same outcome. Clinical review recommended.',
  },
  {
    id: 'ep-002',
    title: '2025 Hospitalization Episode',
    startDate: '2025-02-28',
    endDate: '2025-04-10',
    outcome: 'Hospitalization. Recovery with home care.',
    severity: 'CRITICAL',
    _demo: true,
    symptoms: ['Cough', 'Fever', 'Breathing difficulty', 'Appetite loss', 'Fatigue'],
    medicationsInvolved: ['Antibiotics added', '3 medication changes post-discharge'],
    pattern: [
      { event: 'Fatigue reported by family', date: '2025-02-28' },
      { event: 'Appetite reduced', date: '2025-03-05' },
      { event: 'Cough developed', date: '2025-03-10' },
      { event: 'Hospitalization (pneumonia)', date: '2025-03-15' },
      { event: 'Discharge with medications', date: '2025-03-23' },
      { event: 'Functional decline noted', date: '2025-04-10' },
    ],
    similarityScore: 0.61,
    similarityLabel: 'Moderate pattern similarity',
    warning: 'Current episode does not include respiratory symptoms. Pattern similarity is partial.',
  },
  {
    id: 'ep-003',
    title: '2023 Medication Adjustment Episode',
    startDate: '2023-08-15',
    endDate: '2023-10-30',
    outcome: 'Resolved. Medication stabilized.',
    severity: 'WATCH',
    _demo: true,
    symptoms: ['Fatigue', 'Mild appetite change', 'Sleep disruption'],
    medicationsInvolved: ['Antihypertensive adjusted'],
    pattern: [
      { event: 'Medication changed', date: '2023-08-15' },
      { event: 'Fatigue reported', date: '2023-08-22' },
      { event: 'Sleep disrupted', date: '2023-09-01' },
      { event: 'Appetite mildly reduced', date: '2023-09-10' },
      { event: 'Stabilized', date: '2023-10-30' },
    ],
    similarityScore: 0.74,
    similarityLabel: 'Moderate-strong pattern similarity',
    warning: 'This episode resolved without incident. Current episode has additional cognitive observations.',
  },
];

export const demoContradictions = [
  {
    id: 'cont-001',
    type: 'ALLERGY_CONFLICT',
    description: 'Conflicting allergy records across two clinical entries',
    evidenceA: '2025 discharge summary: Penicillin allergy documented (reaction: rash)',
    evidenceB: '2026 outpatient record: No known drug allergies listed',
    currentMedication: 'Amoxicillin currently prescribed',
    detectedAt: '2026-09-08T00:00:00Z',
    status: 'OPEN',
    confidence: 'HIGH',
    severity: 'CRITICAL',
    requiresHumanReview: true,
    _demo: true,
  },
  {
    id: 'cont-002',
    type: 'CONDITION_CONFLICT',
    description: 'Conflicting diabetes diagnosis records',
    evidenceA: '2021 record: Type 2 Diabetes Mellitus, well-controlled',
    evidenceB: '2026 GP note: Pre-diabetic, not yet diagnosed',
    detectedAt: '2026-09-05T00:00:00Z',
    status: 'OPEN',
    confidence: 'MODERATE',
    severity: 'REVIEW',
    requiresHumanReview: true,
    _demo: true,
  },
];

export const demoMissingInfo = [
  {
    id: 'miss-001',
    category: 'COGNITIVE_ASSESSMENT',
    description: 'No formal cognitive assessment in the past 18 months',
    severity: 'REVIEW',
    detectedAt: '2026-09-10T00:00:00Z',
    status: 'OPEN',
    recommendation: 'Consider MMSE or MoCA given recent cognitive observations',
    _demo: true,
  },
  {
    id: 'miss-002',
    category: 'MEDICATION_RECONCILIATION',
    description: 'No complete medication reconciliation since hospitalization in 2025',
    severity: 'REVIEW',
    detectedAt: '2026-09-08T00:00:00Z',
    status: 'OPEN',
    recommendation: 'Full medication reconciliation recommended given multiple medication changes',
    _demo: true,
  },
  {
    id: 'miss-003',
    category: 'FALL_RISK_ASSESSMENT',
    description: 'Fall risk assessment outdated (last done March 2025)',
    severity: 'ATTENTION',
    detectedAt: '2026-09-06T00:00:00Z',
    status: 'OPEN',
    recommendation: 'Updated fall risk assessment recommended given mobility changes',
    _demo: true,
  },
  {
    id: 'miss-004',
    category: 'FUNCTIONAL_ASSESSMENT',
    description: 'No standardized functional assessment (ADLs/IADLs) documented this year',
    severity: 'ATTENTION',
    detectedAt: '2026-09-05T00:00:00Z',
    status: 'OPEN',
    recommendation: 'Barthel Index or Katz ADL scale recommended given caregiver reports of needing support',
    _demo: true,
  },
];

export const demoCareCircle = [
  {
    id: 'cc-member-001',
    name: 'Ananya Kumar',
    relationship: 'Daughter',
    role: 'FAMILY_CAREGIVER',
    initials: 'AK',
    observationCount: 18,
    lastActivity: '2026-09-10T08:30:00Z',
    status: 'ACTIVE',
    verificationStatus: 'VERIFIED',
    permissions: ['REPORT_OBSERVATION', 'VIEW_TIMELINE', 'VIEW_MEDICATIONS', 'VIEW_CARE_CIRCLE'],
    _demo: true,
  },
  {
    id: 'cc-member-002',
    name: 'Suresh Kumar',
    relationship: 'Son',
    role: 'FAMILY_CAREGIVER',
    initials: 'SK',
    observationCount: 9,
    lastActivity: '2026-09-08T20:00:00Z',
    status: 'ACTIVE',
    verificationStatus: 'VERIFIED',
    permissions: ['REPORT_OBSERVATION', 'VIEW_TIMELINE', 'VIEW_CARE_CIRCLE'],
    _demo: true,
  },
  {
    id: 'cc-member-003',
    name: 'Rahul Mehta',
    relationship: 'Friend',
    role: 'FAMILY_CAREGIVER',
    initials: 'RM',
    observationCount: 6,
    lastActivity: '2026-09-09T16:00:00Z',
    status: 'ACTIVE',
    verificationStatus: 'IDENTITY_VERIFIED',
    permissions: ['REPORT_OBSERVATION', 'VIEW_OWN_REPORTS'],
    _demo: true,
  },
  {
    id: 'cc-member-004',
    name: 'Meena Iyer',
    relationship: 'Neighbor',
    role: 'FAMILY_CAREGIVER',
    initials: 'MI',
    observationCount: 4,
    lastActivity: '2026-09-08T10:00:00Z',
    status: 'ACTIVE',
    verificationStatus: 'IDENTITY_VERIFIED',
    permissions: ['REPORT_OBSERVATION', 'VIEW_OWN_REPORTS'],
    _demo: true,
  },
  {
    id: 'cc-member-005',
    name: 'Latha Reddy',
    relationship: 'Professional Caregiver',
    role: 'PROFESSIONAL_CAREGIVER',
    initials: 'LR',
    observationCount: 31,
    lastActivity: '2026-09-07T09:00:00Z',
    status: 'ACTIVE',
    verificationStatus: 'CLINICALLY_VERIFIED',
    permissions: ['REPORT_OBSERVATION', 'VIEW_TIMELINE', 'VIEW_MEDICATIONS', 'VIEW_CARE_PLAN'],
    _demo: true,
  },
  {
    id: 'cc-member-006',
    name: 'Dr. Priya Sharma',
    relationship: 'Primary Clinician',
    role: 'CLINICIAN',
    initials: 'PS',
    observationCount: 12,
    lastActivity: '2026-08-28T14:00:00Z',
    status: 'ACTIVE',
    verificationStatus: 'LICENSE_VERIFIED',
    permissions: ['VIEW_ALL', 'ADD_CLINICAL_NOTES', 'REVIEW_AI_SIGNALS'],
    _demo: true,
  },
];

export const demoMedications = [
  {
    id: 'med-001',
    name: 'Metformin',
    genericName: 'Metformin Hydrochloride',
    dosage: '1000mg',
    frequency: 'Twice daily (morning & evening)',
    startedAt: '2021-06-01',
    status: 'ACTIVE',
    prescribedBy: 'Dr. Priya Sharma',
    adherence: 72,
    baselineAdherence: 95,
    recentChange: { date: '2026-09-02', type: 'DOSE_ADJUSTED', description: 'Increased from 500mg' },
    signals: ['ADHERENCE_DECLINE', 'RECENT_CHANGE'],
    _demo: true,
  },
  {
    id: 'med-002',
    name: 'Amlodipine',
    genericName: 'Amlodipine Besylate',
    dosage: '5mg',
    frequency: 'Once daily (evening)',
    startedAt: '2021-08-15',
    status: 'ACTIVE',
    prescribedBy: 'Dr. Priya Sharma',
    adherence: 78,
    baselineAdherence: 96,
    signals: ['ADHERENCE_DECLINE'],
    _demo: true,
  },
  {
    id: 'med-003',
    name: 'Atorvastatin',
    genericName: 'Atorvastatin Calcium',
    dosage: '20mg',
    frequency: 'Once daily (bedtime)',
    startedAt: '2022-03-01',
    status: 'ACTIVE',
    prescribedBy: 'Dr. Priya Sharma',
    adherence: 82,
    baselineAdherence: 94,
    signals: ['ADHERENCE_DECLINE'],
    _demo: true,
  },
  {
    id: 'med-004',
    name: 'Aspirin',
    genericName: 'Acetylsalicylic acid',
    dosage: '75mg',
    frequency: 'Once daily (morning)',
    startedAt: '2020-01-01',
    status: 'ACTIVE',
    prescribedBy: 'Dr. Priya Sharma',
    adherence: 88,
    baselineAdherence: 97,
    signals: [],
    _demo: true,
  },
  {
    id: 'med-005',
    name: 'Amoxicillin',
    genericName: 'Amoxicillin Trihydrate',
    dosage: '500mg',
    frequency: 'Three times daily (7 days)',
    startedAt: '2026-09-05',
    status: 'ACTIVE',
    prescribedBy: 'Dr. Priya Sharma',
    adherence: null,
    signals: ['POTENTIAL_ALLERGY_CONFLICT'],
    _demo: true,
  },
];

export const demoWhatChanged = {
  patientId: DEMO_PATIENT_ID,
  generatedAt: '2026-09-10T10:00:00Z',
  _demo: true,
  changes: [
    {
      id: 'chg-001',
      title: 'Medication adherence decreased significantly',
      detail: 'Down from 95% (personal baseline) to 72% in the past 2 weeks.',
      domain: 'MEDICATION',
      severity: 'CONCERN',
      evidenceCount: 3,
      icon: '💊',
    },
    {
      id: 'chg-002',
      title: 'Mobility well below personal baseline',
      detail: 'Daily steps at 1,950 vs baseline of 3,100 — 37% below normal.',
      domain: 'MOBILITY',
      severity: 'CONCERN',
      evidenceCount: 2,
      icon: '🚶',
    },
    {
      id: 'chg-003',
      title: 'Appetite reduced',
      detail: 'Caregiver and family report reduced meal intake over past 5 days.',
      domain: 'APPETITE',
      severity: 'WATCH',
      evidenceCount: 2,
      icon: '🍽️',
    },
    {
      id: 'chg-004',
      title: 'Cognitive observations increased',
      detail: '4 confusion/memory-related observations in past 2 weeks. Baseline: rare.',
      domain: 'COGNITIVE',
      severity: 'CONCERN',
      evidenceCount: 4,
      icon: '🧠',
    },
    {
      id: 'chg-005',
      title: 'Sleep duration reduced',
      detail: 'Sleeping 5.4 hrs vs baseline of 7 hrs. Night waking reported.',
      domain: 'SLEEP',
      severity: 'WATCH',
      evidenceCount: 1,
      icon: '😴',
    },
  ],
  whyNow: [
    'Medication (Metformin) changed 8 days ago — dose doubled',
    'Medication adherence declined within days of change',
    '3 Care Circle members independently reported related observations within 7 days',
    'Current pattern partially matches 2024 episode (medication → appetite → mobility → fall)',
    'HbA1c elevated at 7.8% on 20 Aug 2026 lab',
  ],
  corroboration: {
    label: 'Independent corroboration',
    description: '3 Care Circle members reported related observations within 7 days',
    reporters: ['Ananya Kumar (Daughter)', 'Meena Iyer (Neighbor)', 'Suresh Kumar (Son)'],
  },
  disclaimer:
    'These are reported observations and AI-detected patterns, not clinical diagnoses. All signals require clinician review.',
};

export const demoClinicalBrief = {
  patientId: DEMO_PATIENT_ID,
  generatedAt: '2026-09-10T10:30:00Z',
  _demo: true,
  _aiGenerated: true,
  _disclaimer:
    'AI-generated summary for clinical review. Not a diagnosis. Clinician must independently assess all findings.',
  sections: {
    currentChanges:
      'Ravi Kumar (76M) is showing meaningful changes across multiple domains over the past 2 weeks. Medication adherence has decreased from a baseline of 95% to 72%. Daily mobility has dropped to 1,950 steps/day from a baseline of 3,100 steps/day (37% decline). Four confusion-related observations have been reported by Care Circle members — significantly above his personal baseline of rare cognitive observations. Appetite has decreased, and sleep duration has shortened to 5.4 hours from a baseline of 7 hours.',
    relevantHistory:
      'Ravi has a history of Type 2 Diabetes Mellitus, hypertension, and hyperlipidemia. He was hospitalized in March 2025 for pneumonia (8 days). He experienced a fall in February 2024 (ER visit) and a second fall in August 2025 (minor wrist injury). He has historically been independent in all activities of daily living and medication management.',
    careCircleObservations:
      'Multiple Care Circle members have independently reported related observations within 7 days. Daughter (Ananya) reported medication missed and confusion about dates. Son (Suresh) observed repetitive questioning. Neighbor (Meena) noted absence from morning walks. Professional caregiver (Latha) confirmed medication missed from pill box. Friend (Rahul) reported unusual fatigue.',
    medicationContext:
      'Metformin dose was increased from 500mg to 1000mg twice daily on 2 Sep 2026 — 8 days ago. This coincides with the onset of adherence decline and appetite changes. Amlodipine and Atorvastatin adherence have also declined. A potential allergy conflict exists: 2025 records document penicillin allergy (rash), while 2026 outpatient record documents no known drug allergies. Amoxicillin (a penicillin-class antibiotic) is currently prescribed.',
    cognitiveChanges:
      'Four cognitive/memory-related observations have been reported in the past 2 weeks — a meaningful increase above baseline (rare, occasional). Observations include confusion about dates, repetitive questioning, and what was described as general disorientation. These are REPORTED observations, not clinically verified. No formal cognitive assessment has been completed in 18 months.',
    functionalChanges:
      'Mobility has significantly decreased below personal baseline. Care Circle reports that he is not taking his habitual morning walk. He reportedly needs increasing assistance. No standardized functional assessment (ADL/IADL) has been completed this year.',
    historicalEpisodeMatch:
      'The current pattern shows strong similarity (82%) to a 2024 episode: medication change → appetite reduction → mobility decline → dizziness → fall → ER visit. The 2023 episode (medication change → fatigue → sleep disruption → appetite change → stabilization) shows moderate-strong similarity (74%). Pattern similarity does not establish causation or predict the same outcome.',
    suggestedAreasForClinicalReview: [
      'Review Metformin dose increase in context of appetite, adherence and cognitive changes',
      'Clarify penicillin allergy status — current Amoxicillin prescription requires urgent review',
      'Consider formal cognitive assessment (MMSE or MoCA) given recent cognitive observations',
      'Fall risk assessment recommended given mobility decline and 2024/2025 fall history',
      'Complete medication reconciliation',
      'Review functional status and ADL/IADL needs',
    ],
  },
};

export const demoPatients = [
  {
    id: DEMO_PATIENT_ID,
    firstName: 'Ravi',
    lastName: 'Kumar',
    dateOfBirth: '1950-03-15',
    gender: 'Male',
    status: 'ACTIVE',
    currentYearStatus: 'WATCH',
    primaryDoctor: 'Dr. Priya Sharma',
    lastReview: '2026-08-28',
    careCircleCount: 6,
    pendingChanges: 5,
    _demo: true,
  },
  {
    id: 'demo-patient-002',
    firstName: 'Lakshmi',
    lastName: 'Raghavan',
    dateOfBirth: '1948-07-22',
    gender: 'Female',
    status: 'ACTIVE',
    currentYearStatus: 'STABLE',
    primaryDoctor: 'Dr. Priya Sharma',
    lastReview: '2026-09-01',
    careCircleCount: 4,
    pendingChanges: 1,
    _demo: true,
  },
  {
    id: 'demo-patient-003',
    firstName: 'Mohan',
    lastName: 'Pillai',
    dateOfBirth: '1944-11-08',
    gender: 'Male',
    status: 'ACTIVE',
    currentYearStatus: 'CONCERN',
    primaryDoctor: 'Dr. Arjun Nair',
    lastReview: '2026-08-15',
    careCircleCount: 3,
    pendingChanges: 3,
    _demo: true,
  },
];
