'use client';

import { AlertTriangle, Brain, ShieldCheck } from 'lucide-react';
import { cn } from '@/lib/utils';

interface AiResponseBlockProps {
  children: React.ReactNode;
  confidence?: number | null; // 0–100, shown as plain number badge
  className?: string;
}

export const AI_DISCLAIMER =
  '⚠️ This output is generated by an AI model and is intended to assist—not replace—clinical judgement. ' +
  'It may contain errors, omissions, or out-of-date information. ' +
  'The attending clinician must independently verify all findings before acting on this information. ' +
  'This tool is not a substitute for professional medical advice, diagnosis, or treatment. ' +
  'Comply with applicable regulations and institutional protocols before use in patient care.';

/**
 * Wraps AI-generated content with:
 *  • "AI Generated" chip + confidence score number
 *  • Mandatory medical disclaimer
 */
export function AiResponseBlock({ children, confidence, className }: AiResponseBlockProps) {
  return (
    <div className={cn('space-y-3', className)}>
      {/* Content with AI chip + confidence number */}
      <div className="relative">
        {children}
        <div className="absolute top-2 right-2 flex items-center gap-1.5">
          {confidence != null && (
            <span className="inline-flex items-center gap-1 rounded-full bg-blue-50 border border-blue-200 px-2 py-0.5 text-[10px] font-bold text-blue-700 select-none">
              <ShieldCheck className="h-3 w-3" />
              Confidence: {confidence}%
            </span>
          )}
          <span className="inline-flex items-center gap-1 rounded-full bg-primary/10 px-2 py-0.5 text-[10px] font-semibold text-primary border border-primary/20 select-none">
            <Brain className="h-3 w-3" /> AI Generated
          </span>
        </div>
      </div>

      {/* Mandatory disclaimer */}
      <div className="rounded-lg border border-amber-200 bg-amber-50 p-3 flex items-start gap-2">
        <AlertTriangle className="h-4 w-4 text-amber-600 flex-shrink-0 mt-0.5" />
        <p className="text-[11px] leading-relaxed text-amber-800">{AI_DISCLAIMER}</p>
      </div>
    </div>
  );
}
